# script créé le : Tue May 05 12:13:04 CEST 2015 -   syntaxe MySQL ;

# use  VOTRE_BASE_DE_DONNEE ;

DROP TABLE IF EXISTS USER ;
CREATE TABLE USER (ID_USER int AUTO_INCREMENT NOT NULL,
MAIL VARCHAR(50),
PASSWORD VARCHAR(20),
PRIMARY KEY (ID_USER) ) ;

DROP TABLE IF EXISTS VOTE ;
CREATE TABLE VOTE (ID_VOTE int AUTO_INCREMENT NOT NULL,
NOM_VOTE VARCHAR(20),
DESCRIPTION_VOTE LONGTEXT,
DATE_START_VOTE DATE,
DATE_VOTE_END DATE,
RESULT_VOTE LONGTEXT,
STATUT_VOTE VARCHAR(20),
ID_USER INT NOT NULL,
PRIMARY KEY (ID_VOTE) ) ;

DROP TABLE IF EXISTS RULE ;
CREATE TABLE RULE (ID_RULE int AUTO_INCREMENT NOT NULL,
DESCRIPTION_RULE LONGTEXT,
PRIMARY KEY (ID_RULE) ) ;

DROP TABLE IF EXISTS CANDIDATE ;
CREATE TABLE CANDIDATE (ID_CANDIDATE int AUTO_INCREMENT NOT NULL,
NOM_CANDIDATE VARCHAR(20),
DESCRIPTION_CANDIDATE LONGTEXT,
ID_VOTE INT NOT NULL,
PRIMARY KEY (ID_CANDIDATE) );

DROP TABLE IF EXISTS GROUP ;
CREATE TABLE GROUP (ID_GROUP int AUTO_INCREMENT NOT NULL,
NOM_GROUP VARCHAR(20),
DESCRIPTION_GROUP LONGTEXT,
PRIMARY KEY (ID-GROUP) ) ;

DROP TABLE IF EXISTS TYPE ;
CREATE TABLE TYPE (ID_TYPE int AUTO_INCREMENT NOT NULL,
NOM_TYPE VARCHAR(20),
DESCRIPTION_TYPE TEXT,
PRIMARY KEY (ID_TYPE) ) ;

DROP TABLE IF EXISTS PROCURATION ;
CREATE TABLE PROCURATION (ID_USER1 BIGINT NOT NULL,
ID_USER2 BIGINT,
ID_VOTE INT NOT NULL,
PRIMARY KEY (ID_USER1,ID_USER2) ) ;

DROP TABLE IF EXISTS PARTICIPATE ;
CREATE TABLE PARTICIPATE (ID_VOTE int AUTO_INCREMENT NOT NULL,
ID_USER INT NOT NULL,
CHOIX TEXT,
PRIMARY KEY (ID_VOTE,
 ID_USER) ) ;

DROP TABLE IF EXISTS SETUP ;
CREATE TABLE SETUP (ID_VOTE int AUTO_INCREMENT NOT NULL,
ID_RULE INT NOT NULL,
PRIMARY KEY (ID_VOTE,
 ID_RULE) ) ;

DROP TABLE IF EXISTS HAS ;
CREATE TABLE HAS (ID_USER int AUTO_INCREMENT NOT NULL,
ID_USER_HAS INT,
PRIMARY KEY (ID_USER) ) ;

DROP TABLE IF EXISTS BELONGS ;
CREATE TABLE BELONGS (ID_USER int AUTO_INCREMENT NOT NULL,
ID-GROUP INT NOT NULL,
PRIMARY KEY (ID_USER,
 ID-GROUP) ) ;

DROP TABLE IF EXISTS CERTIFIE ;
CREATE TABLE CERTIFIE (ID_VOTE int AUTO_INCREMENT NOT NULL,
ID_TYPE INT NOT NULL,
PRIMARY KEY (ID_VOTE,
 ID_TYPE) ) ;

DROP TABLE IF EXISTS AUTORISER ;
CREATE TABLE AUTORISER (ID_RULE int AUTO_INCREMENT NOT NULL,
ID_TYPE INT NOT NULL,
PRIMARY KEY (ID_RULE,
 ID_TYPE) ) ;

DROP TABLE IF EXISTS AUTORISE ;
CREATE TABLE AUTORISE (ID_USER int AUTO_INCREMENT NOT NULL,
ID_USER1 BIGINT NOT NULL,
PRIMARY KEY (ID_USER,
 ID_USER1) ) ;

