CREATE DATABASE IF NOT EXISTS base_projet;
USE base_projet;

DROP TABLE IF EXISTS UTILISATEUR ;
CREATE TABLE UTILISATEUR (ID_UTILISATEUR INT  AUTO_INCREMENT NOT NULL,
MAIL VARCHAR(50),
MOT_DE_PASSE VARCHAR(20),
PRIMARY KEY (ID_UTILISATEUR) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS VOTE ;
CREATE TABLE VOTE (ID_VOTE INT  AUTO_INCREMENT NOT NULL,
NOM_VOTE VARCHAR(20),
DESCRIPTION_VOTE LONGTEXT,
DATE_DEBUT_VOTE DATE,
DATE_FIN_VOTE DATE,
RESULTAT_VOTE LONGTEXT,
STATUT_VOTE VARCHAR(20),
ID_UTILISATEUR INT,
PRIMARY KEY (ID_VOTE) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS REGLE ;
CREATE TABLE REGLE (ID_REGLE INT  AUTO_INCREMENT NOT NULL,
DESCRIPTION_REGLE LONGTEXT,
PRIMARY KEY (ID_REGLE) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS CANDIDAT ;
CREATE TABLE CANDIDAT (ID_CANDIDAT INT  AUTO_INCREMENT NOT NULL,
NOM_CANDIDAT VARCHAR(20),
DESCRIPTION_CANDIDAT LONGTEXT,
ID_VOTE INT NOT NULL,
PRIMARY KEY (ID_CANDIDAT) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS GROUPE ;
CREATE TABLE GROUPE (ID_GROUP INT  AUTO_INCREMENT NOT NULL,
NOM_GROUP VARCHAR(20),
DESCRIPTION_GROUP LONGTEXT,
PRIMARY KEY (ID_GROUP) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS TYPE ;
CREATE TABLE TYPE (ID_TYPE INT  AUTO_INCREMENT NOT NULL,
NOM_TYPE VARCHAR(20),
DESCRIPTION_TYPE TEXT,
PRIMARY KEY (ID_TYPE) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS PROCURATION ;
CREATE TABLE PROCURATION (ID_USER1 INT  AUTO_INCREMENT NOT NULL,
ID_USER2 INT,
ID_VOTE INT NOT NULL,
PRIMARY KEY (ID_USER1) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS PARTICIPATE ;
CREATE TABLE PARTICIPATE (ID_VOTE INT  AUTO_INCREMENT NOT NULL,
ID_UTILISATEUR INT NOT NULL,
CHOIX TEXT,
PRIMARY KEY (ID_VOTE,
 ID_UTILISATEUR) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS PARAMETRE ;
CREATE TABLE PARAMETRE (ID_VOTE INT  AUTO_INCREMENT NOT NULL,
ID_REGLE INT NOT NULL,
PRIMARY KEY (ID_VOTE,
 ID_REGLE) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS A_CONTACT ;
CREATE TABLE A_CONTACT (ID_UTILISATEUR1 INT NOT NULL,
ID_UTILISATEUR2 INT,
PRIMARY KEY (ID_UTILISATEUR1, ID_UTILISATEUR2) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS APPARTIENT ;
CREATE TABLE APPARTIENT (ID_UTILISATEUR INT  AUTO_INCREMENT NOT NULL,
ID_GROUP INT NOT NULL,
PRIMARY KEY (ID_UTILISATEUR,
 ID_GROUP) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS CERTIFIE ;
CREATE TABLE CERTIFIE (ID_VOTE INT  AUTO_INCREMENT NOT NULL,
ID_TYPE INT NOT NULL,
PRIMARY KEY (ID_VOTE,
 ID_TYPE) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS AUTORISE ;
CREATE TABLE AUTORISE (ID_REGLE INT  AUTO_INCREMENT NOT NULL,
ID_TYPE INT NOT NULL,
PRIMARY KEY (ID_REGLE,
 ID_TYPE) ) ENGINE=InnoDB;

DROP TABLE IF EXISTS DONNE ;
CREATE TABLE DONNE (ID_UTILISATEUR INT  AUTO_INCREMENT NOT NULL,
ID_USER1 INT NOT NULL,
PRIMARY KEY (ID_UTILISATEUR,
 ID_USER1) ) ENGINE=InnoDB;

ALTER TABLE VOTE ADD CONSTRAINT FK_VOTE_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR (ID_UTILISATEUR);

ALTER TABLE CANDIDAT ADD CONSTRAINT FK_CANDIDAT_ID_VOTE FOREIGN KEY (ID_VOTE) REFERENCES VOTE (ID_VOTE);
ALTER TABLE PROCURATION ADD CONSTRAINT FK_PROCURATION_ID_VOTE FOREIGN KEY (ID_VOTE) REFERENCES VOTE (ID_VOTE);
ALTER TABLE PARTICIPATE ADD CONSTRAINT FK_PARTICIPATE_ID_VOTE FOREIGN KEY (ID_VOTE) REFERENCES VOTE (ID_VOTE);
ALTER TABLE PARTICIPATE ADD CONSTRAINT FK_PARTICIPATE_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR (ID_UTILISATEUR);
ALTER TABLE PARAMETRE ADD CONSTRAINT FK_PARAMETRE_ID_VOTE FOREIGN KEY (ID_VOTE) REFERENCES VOTE (ID_VOTE);
ALTER TABLE PARAMETRE ADD CONSTRAINT FK_PARAMETRE_ID_REGLE FOREIGN KEY (ID_REGLE) REFERENCES REGLE (ID_REGLE);
ALTER TABLE A_CONTACT ADD CONSTRAINT FK_A_CONTACT_ID_UTILISATEUR1 FOREIGN KEY (ID_UTILISATEUR1) REFERENCES UTILISATEUR (ID_UTILISATEUR);
ALTER TABLE A_CONTACT ADD CONSTRAINT FK_A_CONTACT_ID_UTILISATEUR2 FOREIGN KEY (ID_UTILISATEUR2) REFERENCES UTILISATEUR (ID_UTILISATEUR);
ALTER TABLE APPARTIENT ADD CONSTRAINT FK_APPARTIENT_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR (ID_UTILISATEUR);
ALTER TABLE APPARTIENT ADD CONSTRAINT FK_APPARTIENT_ID_GROUP FOREIGN KEY (ID_GROUP) REFERENCES GROUPE (ID_GROUP);
ALTER TABLE CERTIFIE ADD CONSTRAINT FK_CERTIFIE_ID_VOTE FOREIGN KEY (ID_VOTE) REFERENCES VOTE (ID_VOTE);
ALTER TABLE CERTIFIE ADD CONSTRAINT FK_CERTIFIE_ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES TYPE (ID_TYPE);
ALTER TABLE AUTORISE ADD CONSTRAINT FK_AUTORISE_ID_REGLE FOREIGN KEY (ID_REGLE) REFERENCES REGLE (ID_REGLE);
ALTER TABLE AUTORISE ADD CONSTRAINT FK_AUTORISE_ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES TYPE (ID_TYPE);
ALTER TABLE DONNE ADD CONSTRAINT FK_DONNE_ID_UTILISATEUR FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR (ID_UTILISATEUR);
ALTER TABLE DONNE ADD CONSTRAINT FK_DONNE_ID_USER1 FOREIGN KEY (ID_USER1) REFERENCES PROCURATION (ID_USER1);
