ALTER TABLE utilisateur DROP FOREIGN KEY UNQ_utilisateur_0
ALTER TABLE vote DROP FOREIGN KEY FK_vote_ID_UTILISATEUR
ALTER TABLE vote DROP FOREIGN KEY FK_vote_ID_TYPE
ALTER TABLE resultat DROP FOREIGN KEY FK_resultat_ID_VOTE
ALTER TABLE resultat DROP FOREIGN KEY FK_resultat_ID_CANDIDAT
ALTER TABLE regle DROP FOREIGN KEY UNQ_regle_0
ALTER TABLE candidat DROP FOREIGN KEY FK_candidat_ID_VOTE
ALTER TABLE participe DROP FOREIGN KEY FK_participe_ID_UTILISATEUR
ALTER TABLE participe DROP FOREIGN KEY FK_participe_ID_CANDIDAT
ALTER TABLE participe DROP FOREIGN KEY FK_participe_ID_VOTE
ALTER TABLE participe DROP FOREIGN KEY UNQ_participe_0
ALTER TABLE delegue DROP FOREIGN KEY FK_delegue_ID_VOTE
ALTER TABLE delegue DROP FOREIGN KEY FK_delegue_ID_UTILISATEUR
ALTER TABLE delegue DROP FOREIGN KEY FK_delegue_ID_MANDATAIRE
ALTER TABLE delegue DROP FOREIGN KEY UNQ_delegue_0
ALTER TABLE a_contact DROP FOREIGN KEY FK_a_contact_ID_CONTACT
ALTER TABLE a_contact DROP FOREIGN KEY FK_a_contact_ID_UTILISATEUR
ALTER TABLE appartient DROP FOREIGN KEY FK_appartient_ID_GROUPE
ALTER TABLE appartient DROP FOREIGN KEY FK_appartient_ID_UTILISATEUR
ALTER TABLE invitation DROP FOREIGN KEY FK_invitation_ID_UTILISATEUR
ALTER TABLE invitation DROP FOREIGN KEY FK_invitation_ID_VOTE
ALTER TABLE parametre DROP FOREIGN KEY FK_parametre_ID_REGLE
ALTER TABLE parametre DROP FOREIGN KEY FK_parametre_ID_VOTE
ALTER TABLE autorise DROP FOREIGN KEY FK_autorise_ID_TYPE
ALTER TABLE autorise DROP FOREIGN KEY FK_autorise_ID_REGLE
DROP TABLE utilisateur
DROP TABLE vote
DROP TABLE resultat
DROP TABLE type
DROP TABLE regle
DROP TABLE candidat
DROP TABLE participe
DROP TABLE groupe
DROP TABLE delegue
DROP TABLE a_contact
DROP TABLE appartient
DROP TABLE invitation
DROP TABLE parametre
DROP TABLE autorise
